/**
 * e-Science Central
 * Copyright (C) 2008-2013 School of Computing Science, Newcastle University
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 as published by the Free Software Foundation at:
 * http://www.gnu.org/licenses/gpl-2.0.html
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, 5th Floor, Boston, MA 02110-1301, USA.
 */
package com.connexience.server.model.logging.performance;

import java.io.Serializable;

/**
 * This class contains a prediction generated by a model. It holds the predicted
 * value and also some upper and lower bounds data.
 * @author hugo
 */
public class PerformanceModelPrediction implements Serializable {
    private static final long serialVersionUID = 1L;
    private boolean valuePresent;
    private double predictedValue;
    private double upper95Bound;
    private double lower95Bound;

    public PerformanceModelPrediction() {
        valuePresent = false;
    }

    public PerformanceModelPrediction(double predictedValue, double upper95Bound, double lower95Bound) {
        this.predictedValue = predictedValue;
        this.upper95Bound = upper95Bound;
        this.lower95Bound = lower95Bound;
        valuePresent = true;
    }

    public void setLower95Bound(double lower95Bound) {
        this.lower95Bound = lower95Bound;
    }

    public void setPredictedValue(double predictedValue) {
        this.predictedValue = predictedValue;
    }

    public void setUpper95Bound(double upper95Bound) {
        this.upper95Bound = upper95Bound;
    }

    public double getLower95Bound() {
        return lower95Bound;
    }

    public double getPredictedValue() {
        return predictedValue;
    }

    public double getUpper95Bound() {
        return upper95Bound;
    }

    public void setValuePresent(boolean valuePresent) {
        this.valuePresent = valuePresent;
    }

    public boolean isValuePresent() {
        return valuePresent;
    }
}